### ISSUE TITLE
How to remove the bootlogo patcher.

### ISSUE THREAD

**Issue by HyphyOP** [corsicanu/TWRP_Bootlogo_patcher#1]
Hey so I used this to remove the warning screen on my Samsung Galaxy A10 but now after using this my phone is constantly crashing and I want to remove this. Do you know how I can do it

**Comment by corsicanu** [comment]
Reflash param.bin and up_param.bin from stock firmware BL_* file.
Just a fyi, your crashes have nothing to do with the patcher, as you can see in readme this zip only changes a drawable asset, which is only loaded in early bootloader stage.

**Comment by HyphyOP** [comment]
I mean I was just playing PUBG before it and it was fine so it should be that only. Well Thanks.
