### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by furjac** [corsicanu/TWRP_Bootlogo_patcher#12]
@corsicanu so thanks for the previous versions but for the latest stock m21 its not working it says like this
![Screenshot_2024-04-27-07-29-46 1](https://github.com/corsicanu/TWRP_Bootlogo_patcher/assets/81816200/5958ae1a-e432-487e-a7a1-4c34247a20fe)
so is this like my issue or is this from ur side idk so see whatever

**Comment by corsicanu** [comment]
Are you running encrypted?

**Comment by corsicanu** [comment]
Try to flash it again and then pull /tmp/bootloader.log, it might contain some info

**Comment by furjac** [comment]
no it works it was my mistake i didnt disable encryption sorry bro
