### ISSUE TITLE
Samsung Galaxy Tab S5e / SM-T720 / gts4lv

### ISSUE THREAD

**Issue by TLOMT** [corsicanu/TWRP_Bootlogo_patcher#9]
Hi Razvan,

thanks for your great tools, you share with us!

I would be grateful, if your TWRP boot logo patcher could also support in future the device

Samsung Galaxy Tab S5e / SM-T72x / gts4lv[wifi]

Thanks and regards,
Andreas

**Comment by corsicanu** [comment]
Hello and thanks for the good words, unfortunately that tablet is snapdragon and it can't be patched. 
I did some research in the past (i have Tab S6) and found out that snapdragons are not accepting unsigned bootloader files like exynos or some mtk do with param (so far). 

Cheers,
Corsicanu
